#!/bin/bash

yt-dlp -v -N 64 -ci --cookies "cookies.txt" --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" --flat-playlist --print "<p>%(channel)s <---> <strong>%(title)s</strong> <---> <a href=\"%(webpage_url)s\">Link</a></p><p>Live: %(live_status)s , Duration: %(duration_string)s , Views: %(view_count)s</p><br><br><br>" -I 1:1000 "https://www.youtube.com/feed/subscriptions" > feed.html
