#!/bin/bash
Url=$1
DefaultQual="bv[height<=720]+ba"
echo "Loading format list..."&
yt-dlp -v -N 64 -ci --no-overwrites --retries 10 --fragment-retries 10 --cookies "cookies.txt" --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" -F "$Url"
echo "What quality? (Press Enter for 720p or lower):"
read -r Qual
Qual=${Qual:-$DefaultQual}
yt-dlp -v -N 64 -ci --concurrent-fragments 16 --no-overwrites --retries 10 --fragment-retries 10 --cookies "cookies.txt" --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" -f "$Qual" "$Url"
wait