#!/bin/bash
#generic media downloader using yt-dlp - extract source links
Url=$1
echo "Loading format list..."&
yt-dlp -v -N 1000 -ci --cookies-from-browser firefox --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" -F "$Url"
echo "What quality?(video+audio or single stream):"
read -r Qual
Sources=()
while IFS= read -r line; do
	Sources+=( "$line" )
done < <( yt-dlp -v -N 1000 -ci --cookies-from-browser firefox -g -f "$Qual" "$Url" )
for SourceLine in "${Sources[@]}"; do
	echo -e "\n---------------------------\n"
	echo "$SourceLine"
	echo -e "\n---------------------------\n"
done