#!/bin/bash

if [[ $# -eq 0 ]] ; then
    printf 'File Merger\nUsage: merger [directory to search] [filename of output file]\n';
    exit 0;
fi

find $1 -type f -printf '\n\n\n\n======> %p <======\n\n\n\n' -execdir cat '{}' \; > $2.txt;
printf '\n\n\n\n TREE OF FILES:\n\n' >> $2.txt;
tree -a $1 >> $2.txt;