#!/bin/bash

link="$(youtube-dl -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' -g "$1")"

ffmpeg -hide_banner -loglevel panic -nostats -i "$link" -c:v copy -c:a copy ~/temp.mkv&

while [[ ! -f ~/temp.mkv ]];
do
	sleep 5s
done

mpv ~/temp.mkv

wait

killall -9 ffmpeg
killall -9 mpv

rm ~/temp.mkv

reset

