#!/bin/bash

#Too complex just for fun and security :)

link="$(youtube-dl -f bestaudio/best -g "$1")"

ffmpeg -hide_banner -loglevel panic -nostats -i "$link" -c:a copy -vn ~/temp.mkv&

while [[ ! -f ~/temp.mkv ]];
do
	sleep 5s
done

mpv --no-video ~/temp.mkv

wait

killall -9 ffmpeg
killall -9 mpv

rm ~/temp.mkv

reset

