#!/usr/bin/env python3

import csv
import sys

input_file = sys.argv[1]
output_file = input_file.rsplit('.', 1)[0] + '-quoted.csv' 

with open(input_file, 'r') as file_in, open(output_file, 'w', newline='') as file_out:
    reader = csv.reader(file_in)
    writer = csv.writer(file_out, quoting=csv.QUOTE_ALL)

    for row in reader:
        writer.writerow(row)
