server:

    interface: 0.0.0.0@853
    interface: ::0@853
    tls-port: 853

    interface: 0.0.0.0@443
    interface: ::0@443
    https-port: 443

    access-control: 0.0.0.0/0 allow
    access-control: ::0/0 allow

    do-ip4: yes
    do-ip6: yes
    do-tcp: yes

    do-udp: no

    udp-upstream-without-downstream: yes

    module-config: "iterator"

    logfile: ""
    verbosity: 0
    log-queries: no
    log-replies: no
    log-servfail: no
    log-local-actions: no
    statistics-interval: 0
    extended-statistics: no
    val-log-level: 0

    hide-identity: yes
    hide-version: yes

    qname-minimisation: yes

    tls-service-key: "/etc/letsencrypt/live/[your domain here]/privkey.pem"
    tls-service-pem: "/etc/letsencrypt/live/[your domain here]/fullchain.pem"
    